### ISSUE TITLE
Have navigation bar

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/week1-BAJA#5]
Be able to click on a navigation link and a corresponding section be made visible in the browser window on the same page
Allow users to quickly navigate around the site without having to wait for new pages to be loaded.

Different nav bar for mobile and desktop

**Comment by BartBucknill** [comment]
mobile and desktop navbar working with JS

**Comment by BartBucknill** [comment]
mobile and desktop navbar working with JS
